enable-merge-back: true
target-folder: docs
target-file-name: README.md
included:
  - src/app
  - api
excluded:
  - .tox/
  - __pycache__/
  - .git/
  - .gitignore
  - .env
  - .env.local
  - .env.development.local
  - .env.test.local
  - .env.production.local
  - .env.development
  - .env.test